"""empty message

Revision ID: a732c40daacf
Revises: c5f13a159b0e
Create Date: 2021-01-30 22:59:48.584541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a732c40daacf'
down_revision = 'c5f13a159b0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('is_manager', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('public_id', sa.String(length=50), nullable=True))
    op.create_unique_constraint(None, 'users', ['public_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'public_id')
    op.drop_column('users', 'is_manager')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
